### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by odyright** [responsiv/angular-plugin#7]
hello guy! good work, i still learning dev with laravel and angularjs and iwan't to know how to install it? from scratch please..

**Comment by odyright** [comment]
???

**Comment by vojtasvoboda** [comment]
Install OctoberCMS (http://octobercms.com/docs/setup/installation), copy this repository to folder /plugins/responsiv/angular.

**Comment by odyright** [comment]
Hi, good job thanks!
