### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by VitruxPT** [responsiv/angular-plugin#9]
Hi @daftspunk,

I've been trying for almost 2 weeks now to setup this plugin with october so i can get my angular working but i just can't seem to be able to do this.

I don't really understand how i should have the pages setup and the layout and yes i've read the "readme" file but i still can't do this.

I don't really know what i should put in the routes script to work with october.

For example, this is my routes script:

```
//Define an angular module for our app
var sampleApp = angular.module('sampleApp', ['ngRoute']);

//Define Routing for app

sampleApp.config(['$routeProvider',
  function($routeProvider) {
    $routeProvider.
      when('/AddNewOrder', {
        templateUrl: 'add_order', //page placed in pages/add_order.htm
        controller: 'AddOrderController'
    }).
      when('/ShowOrders', {
        templateUrl: 'show_orders', //page placed in pages/show_orders.htm
        controller: 'ShowOrdersController'
      }).
      otherwise({
        redirectTo: '/AddNewOrder'
      });
}]);


sampleApp.controller('AddOrderController', function($scope) {

    $scope.message = 'This is Add new order screen';

});


sampleApp.controller('ShowOrdersController', function($scope) {

    $scope.message = 'This is Show orders screen';

});
```

Can you give me a little help?

**Comment by daftspunk** [comment]
The route table is supposed to be generated automatically by the ngLayout component. This plugin was a discontinued experiment, I'm not sure if it still works. Sorry about that...

**Comment by VitruxPT** [comment]
Np i guess.
Are you planning on doing a similar plugin in the future? Because this really would help people that are new into angular and want to work with it in October. As one of those people i can say that it would help me a lot.

**Comment by scottbedard** [comment]
@VitruxPT if you're willing to use Vue for your SPA, this theme might be of interest to you.
https://github.com/scottbedard/oc-vuetober-theme

**Comment by VitruxPT** [comment]
@scottbedard I will certainly look into it. Thank you so much!

**Comment by daftspunk** [comment]
Thanks @VitruxPT and @scottbedard, we may revisit this plugin again. To be honest we were waiting to see what happened with Angular 2. In fact, in giving this more attention, we would probably rewrite it to use Vue.js anyway.
